import React, { useEffect, useState } from 'react';
import { readSession } from '../lib/session';
import { go } from '../lib/navigation';

export function Logo(){ return <button className="logo" onClick={()=>go('/')} aria-label="Về trang chủ"><span className="logo-mark"><i/><i/><i/></span><span>Career<br/><b>Compass</b></span></button> }
export function Header({page}){const [session,setSession]=useState(readSession());useEffect(()=>{const f=()=>setSession(readSession());addEventListener('career-session-change',f);return()=>removeEventListener('career-session-change',f)},[]);return <header><Logo/><nav aria-label="Điều hướng chính"><button className={page==='profile'?'active':''} onClick={()=>go('/profile')}>Hồ sơ của tôi</button><button className={page==='abilities'?'active':''} onClick={()=>go('/abilities')}>Năng lực</button><button className={page==='careers'?'active':''} onClick={()=>go('/careers')}>Nghề phù hợp</button><button disabled={!session.selectedCareerId} title={!session.selectedCareerId?'Chọn một nghề trước để tạo lộ trình':''} className={page==='roadmap'?'active':''} onClick={()=>go('/roadmap/'+session.selectedCareerId)}>Lộ trình {!session.selectedCareerId&&<small>Khóa</small>}</button><button className={page==='companion'?'active':''} onClick={()=>go('/companion')}>Đồng hành</button></nav><button className="header-login" onClick={()=>go('/login')}>Đăng nhập</button></header>}
export function Pill({children,tone=''}){return <span className={'pill '+tone}>{children}</span>}
export function Progress({value}){return <div className="progress"><i style={{width:value+'%'}}/></div>}

export function EmptyData({text}){return <div className="empty-data"><span>∅</span><p>{text}</p></div>}

export function Home(){return <><Header/><main className="home"><section className="hero"><div><Pill tone="soft">Định hướng dựa trên chính bạn</Pill><h1>Không cần chọn nghề<br/>chỉ bằng <em>cảm tính.</em></h1><p>Hiểu thế mạnh, khám phá những hướng đi phù hợp và nhận lộ trình học có thể bắt đầu ngay hôm nay.</p><div className="hero-actions"><button className="primary" onClick={()=>go('/assessment')}>Bắt đầu khám phá <span>→</span></button><button className="ghost" onClick={()=>document.querySelector('#how').scrollIntoView({behavior:'smooth'})}>Xem cách hoạt động</button></div><div className="trust"><span>✓ Không phán xét</span><span>✓ Có thể chỉnh sửa</span><span>✓ Dữ liệu lưu trên thiết bị</span></div></div><div className="compass-card"><div className="orbit o1"/><div className="orbit o2"/><div className="needle"><i/><b/></div><div className="float-card fc1"><small>Kết quả năng lực</small><b>Chưa có phân tích</b><span>—</span></div><div className="float-card fc2"><small>Hướng đi gợi ý</small><b>Chưa có phân tích</b><span>—</span></div><div className="spark s1"/><div className="spark s2"/></div></section><section id="how" className="how"><div className="eyebrow">Hành trình của bạn</div><h2>Từ hiểu mình đến một kế hoạch rõ ràng</h2><div className="steps"><article><span>01</span><h3>Khám phá bản thân</h3><p>Chia sẻ sở thích, kỹ năng và những trải nghiệm đã định hình bạn.</p></article><article><span>02</span><h3>Nhìn thấy lựa chọn</h3><p>So sánh nhiều nghề phù hợp, cùng lý do và khoảng cách kỹ năng.</p></article><article><span>03</span><h3>Bắt đầu lộ trình</h3><p>Đi từng bước vừa sức với thời gian, ngân sách và mục tiêu của bạn.</p></article></div></section></main></>}





export function Locked({type='careers'}){return <><Header/><main className="locked page"><div className="lock-mark">CC</div><div className="eyebrow">Nội dung chưa mở khóa</div><h1>{type==='roadmap'?'Hãy chọn một nghề trước khi tạo lộ trình':'Hãy hoàn thành khảo sát trước khi xem nghề'}</h1><p>{type==='roadmap'?'Lộ trình chỉ được tạo sau khi bạn xác nhận hồ sơ và chọn hướng đi phù hợp.':'Gợi ý nghề cần dựa trên câu trả lời và hồ sơ đã được chính bạn xác nhận.'}</p><button className="primary" onClick={()=>go(type==='roadmap'?'/careers':'/assessment')}>{type==='roadmap'?'Xem các nghề phù hợp':'Bắt đầu khảo sát'} <span>→</span></button></main></>}





export function HeaderAI({page}){const [session,setSession]=useState(readSession());useEffect(()=>{const f=()=>setSession(readSession());addEventListener('career-session-change',f);return()=>removeEventListener('career-session-change',f)},[]);const name=session.displayName?.trim()||null;const avatar=name?name.split(' ').slice(-2).map(x=>x[0]).join('').toUpperCase():'AN';return <header><Logo/><nav aria-label="Điều hướng chính"><button className={page==='profile'?'active':''} onClick={()=>go('/profile')}>Hồ sơ</button><button className={page==='abilities'?'active':''} onClick={()=>go('/abilities')}>Năng lực</button><button className={page==='careers'?'active':''} onClick={()=>go('/careers')}>Nghề phù hợp</button><button disabled={!session.selectedCareerId} className={page==='roadmap'?'active':''} onClick={()=>go('/roadmap/'+session.selectedCareerId)}>Lộ trình {!session.selectedCareerId&&<small>Khóa</small>}</button><button className={page==='companion'?'active':''} onClick={()=>go('/companion')}>Đồng hành</button></nav><div className="anonymous-user"><div className="avatar" aria-label={name?`Hồ sơ của ${name}`:'Hồ sơ ẩn danh'}>{avatar}</div><small>{name||'Ẩn danh'}</small></div></header>}
