import React, { useMemo, useState } from 'react';
import { EmptyData, HeaderAI, Pill, Progress } from '../components/common';
import { readSession, saveSession } from '../lib/session';
import { go } from '../lib/navigation';
import { ProfileDataEditor } from './Profile';

const ABILITY_CATALOG=[
  ['analysis_reasoning','Phân tích và suy luận'],['critical_thinking','Tư duy phản biện'],
  ['creativity_ideation','Sáng tạo và tạo ý tưởng'],['learning_adaptability','Học hỏi và thích ứng'],
  ['language_communication','Ngôn ngữ và diễn đạt'],['planning_execution','Lập kế hoạch và thực thi'],
  ['attention_to_detail','Chú ý chi tiết'],['interaction_collaboration','Tương tác và hợp tác'],
];
const RIASEC_LABELS={R:'Thực tế',I:'Nghiên cứu',A:'Sáng tạo',S:'Xã hội',E:'Quản lý',C:'Tổ chức'};

function AbilityRadar({abilities}){
  const size=300,center=150,radius=104;
  const point=(index,factor=1)=>{const angle=-Math.PI/2+index*Math.PI/4;return `${center+Math.cos(angle)*radius*factor},${center+Math.sin(angle)*radius*factor}`};
  const values=ABILITY_CATALOG.map(([id])=>Math.max(0,Math.min(1,(abilities.find(item=>item.abilityId===id)?.score||0)/3)));
  return <div className="profile-radar-wrap"><svg className="profile-radar" width={size} height={size} viewBox={`0 0 ${size} ${size}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label="Biểu đồ radar tám năng lực"><g className="profile-radar-plot">{[1,.75,.5,.25].map(level=><polygon key={level} points={ABILITY_CATALOG.map((_,i)=>point(i,level)).join(' ')} className="profile-radar-grid"/>)}{ABILITY_CATALOG.map((_,i)=><line key={i} x1={center} y1={center} x2={point(i).split(',')[0]} y2={point(i).split(',')[1]} className="profile-radar-axis"/>)}<polygon points={values.map((value,i)=>point(i,value)).join(' ')} className="profile-radar-result"/>{values.map((value,i)=>{const [x,y]=point(i,value).split(',');return <circle key={i} cx={x} cy={y} r="4" className="profile-radar-dot"/>})}</g></svg><div className="radar-legend"><i/><span>Kết quả từ bài đánh giá</span></div></div>
}

export function AbilitiesSchema(){
  const [session,setSession]=useState(readSession());
  const [editing,setEditing]=useState(false);
  const [basic,setBasic]=useState(session.answers?.basic||{});
  const [editingSection,setEditingSection]=useState(null);
  const [interestDraft,setInterestDraft]=useState({current:session.answers?.interestCurrent||session.answers?.interests||[],exploration:session.answers?.interestExploration||[],values:session.answers?.careerValues||[]});
  const [skillsDraft,setSkillsDraft]=useState(session.answers?.skills||[]);
  const [tendencyDraft,setTendencyDraft]=useState(session.aiAnalysis?.workTendencies||[]);
  const [experienceDraft,setExperienceDraft]=useState(session.aiAnalysis?.experiences||[]);
  const [selectedAbility,setSelectedAbility]=useState(session.aiAnalysis?.abilities?.[0]?.abilityId||ABILITY_CATALOG[0][0]);
  const analysis=session.aiAnalysis;
  const interests=session.answers?.interestCurrent||session.answers?.interests||[];
  const exploration=session.answers?.interestExploration||[];
  const values=session.answers?.careerValues||[];
  const skills=session.answers?.skills||[];
  const tendencies=analysis?.workTendencies||[];
  const experiences=analysis?.experiences||[];
  const abilities=analysis?.abilities||[];
  const selected=abilities.find(item=>item.abilityId===selectedAbility);
  const saveBasic=()=>{const next=saveSession({displayName:basic.name?.trim()||null,answers:{...(session.answers||{}),basic},profileStatus:session.profileStatus==='confirmed'?'needs_reconfirmation':session.profileStatus});setSession(next);setEditing(false)};
  const saveSection=(section)=>{let patch={profileStatus:'needs_reconfirmation'};if(section==='interests')patch.answers={...(session.answers||{}),interests:interestDraft.current,interestCurrent:interestDraft.current,interestExploration:interestDraft.exploration,careerValues:interestDraft.values};if(section==='skills')patch.answers={...(session.answers||{}),skills:skillsDraft};if(section==='tendencies')patch.aiAnalysis={...(analysis||{}),workTendencies:tendencyDraft};if(section==='experiences')patch.aiAnalysis={...(analysis||{}),experiences:experienceDraft};const next=saveSession(patch);setSession(next);setEditingSection(null)};
  const checklist=[
    ['Đã nhập thông tin cơ bản',Boolean(basic.level&&basic.region)],
    ['Có ít nhất một sở thích',interests.length>0],
    ['Có ít nhất một kỹ năng',skills.length>0],
    ['Đã xem hồ sơ năng lực',abilities.length>0],
  ];
  const confirmProfile=()=>{const next=saveSession({profileStatus:'confirmed',abilityReviewed:true});setSession(next);go('/careers')};
  return <><HeaderAI page="abilities"/><main className="page profile-schema"><div className="profile-head"><div><div className="eyebrow">Năng lực của tôi</div><h1>{session.displayName?`Bản đồ năng lực của ${session.displayName}`:'Bản đồ năng lực ẩn danh'}</h1><p>Sở thích, kỹ năng, trải nghiệm và bằng chứng từ bài đánh giá được tập trung tại đây. Thông tin cá nhân được quản lý riêng trong mục Hồ sơ.</p></div><div className="completion"><b>{analysis?'100%':'—'}</b><span>{analysis?'Đã tổng hợp năng lực':'Chờ phân tích dữ liệu'}</span></div></div>
  {session.profileStatus==='needs_reconfirmation'&&<div className="notice warning">Thông tin đã thay đổi. Hãy xác nhận lại hồ sơ để cập nhật nghề gợi ý và lộ trình.</div>}
  <div className="profile-layout"><aside aria-label="Các phần năng lực"><a href="#interests" className="current">Sở thích & giá trị</a><a href="#skills">Kỹ năng</a><a href="#tendencies">Xu hướng làm việc</a><a href="#experiences">Trải nghiệm</a><a href="#abilities">Bản đồ năng lực</a><a href="#confirm">Xác nhận năng lực</a><button className="reset-link" onClick={()=>go('/assessment')}>Làm lại khảo sát</button></aside>
  <div className="profile-content">
    <div className="profile-update-toolbar"><div><b>Chỉnh sửa và cập nhật năng lực</b><small>Mỗi nhóm thông tin đều có thể bổ sung dù hiện đang trống.</small></div><div><button onClick={()=>setEditingSection('interests')}>Sở thích & giá trị</button><button onClick={()=>setEditingSection('skills')}>Kỹ năng</button><button onClick={()=>{if(!tendencyDraft.length)setTendencyDraft([['collaboration','Làm việc cùng nhóm'],['structure','Môi trường có cấu trúc'],['change','Thích nghi với thay đổi'],['data_focus','Tập trung vào dữ liệu'],['communication','Giao tiếp thường xuyên'],['method','Tự tìm phương pháp']].map(([id,name])=>({id,name,value:1})));setEditingSection('tendencies')}}>Xu hướng</button><button onClick={()=>setEditingSection('experiences')}>Trải nghiệm</button><button onClick={()=>setEditingSection('abilities')}>Cập nhật đánh giá</button></div></div>
    <ProfileDataEditor section={editingSection} onClose={()=>setEditingSection(null)} onSave={saveSection} interestDraft={interestDraft} setInterestDraft={setInterestDraft} skillsDraft={skillsDraft} setSkillsDraft={setSkillsDraft} tendencyDraft={tendencyDraft} setTendencyDraft={setTendencyDraft} experienceDraft={experienceDraft} setExperienceDraft={setExperienceDraft}/>
    <section className="section-card" id="interests"><div className="section-title"><div><Pill>02</Pill><h2>Sở thích và giá trị nghề nghiệp</h2></div></div><div className="interest-columns"><div><h4>Hoạt động đang yêu thích</h4>{interests.length?<div className="pills">{interests.map(item=><Pill key={item}>{item}</Pill>)}</div>:<EmptyData text="Chưa có hoạt động yêu thích."/>}</div><div><h4>Muốn khám phá</h4>{exploration.length?<div className="pills">{exploration.map(item=><Pill key={item} tone="outline">{item}</Pill>)}</div>:<EmptyData text="Chưa có hoạt động muốn khám phá."/>}</div></div><h4>Giá trị nghề nghiệp theo ưu tiên</h4>{values.length?<ol className="values">{values.map((item,index)=><li key={item}><span>{index+1}</span><b>{item}</b></li>)}</ol>:<EmptyData text="Chưa có giá trị nghề nghiệp được xếp hạng."/>}{analysis?.riasec&&<div className="riasec-strip">{Object.entries(analysis.riasec).map(([key,value])=><div key={key}><b>{key}</b><span>{RIASEC_LABELS[key]}</span><Progress value={value}/><small>{value}/100</small></div>)}</div>}</section>
    <section className="section-card" id="skills"><div className="section-title"><div><Pill>03</Pill><h2>Kỹ năng hiện tại</h2></div><button className="text-btn" onClick={()=>setEditingSection('skills')}>{skills.length?'Cập nhật kỹ năng':'Thêm kỹ năng'}</button></div>{skills.length?<div className="profile-skill-list">{skills.map((skill,index)=><article key={`${skill.name}-${index}`}><div><b>{skill.name}</b><p>{skill.context||'Chưa có mô tả bối cảnh sử dụng.'}</p></div><Pill>{['Chưa bắt đầu','Cơ bản','Khá','Tốt'][Number(skill.level)]||skill.level}</Pill></article>)}</div>:<EmptyData text="Chưa có kỹ năng tự khai."/>}</section>
    <section className="section-card" id="tendencies"><div className="section-title"><div><Pill>04</Pill><h2>Xu hướng làm việc</h2></div></div><p>Đây là mô tả cách làm việc trong bối cảnh hiện tại, không phải nhãn tính cách cố định.</p>{tendencies.length?<div className="tendency-grid">{tendencies.map(item=><div key={item.id}><div><b>{item.name}</b><span>{['Không đúng','Đúng một phần','Khá đúng','Rất đúng'][item.value-1]}</span></div><div className="four-scale" aria-label={`${item.name}: ${item.value} trên 4`}>{[1,2,3,4].map(level=><i key={level} className={level<=item.value?'filled':''}/>)}</div></div>)}</div>:<EmptyData text="Chưa có dữ liệu xu hướng làm việc."/>}{analysis?.habitPatterns?.length>0&&<div className="pattern-list">{analysis.habitPatterns.map(item=><article key={item.pattern_id||item.patternId}><b>{item.label}</b><p>{item.observation}</p><small>Bối cảnh: {(item.contexts||[]).join(', ')||'Chưa xác định'} · Độ tin cậy {Math.round((item.confidence||0)*100)}%</small></article>)}</div>}</section>
    <section className="section-card" id="experiences"><div className="section-title"><div><Pill>05</Pill><h2>Trải nghiệm</h2></div><button className="text-btn" onClick={()=>setEditingSection('experiences')}>{experiences.length?'Cập nhật trải nghiệm':'Thêm trải nghiệm'}</button></div>{experiences.length?<div className="experience-list">{experiences.map(item=><article key={item.id}><small>{item.role||'Vai trò chưa xác định'}</small><h3>{item.title}</h3><p>{item.description}</p><div><span><b>Điều thích</b>{(item.liked_aspects||[]).join(', ')||'—'}</span><span><b>Điều không thích</b>{(item.disliked_aspects||[]).join(', ')||'—'}</span></div>{item.reflection&&<blockquote>{item.reflection}</blockquote>}</article>)}</div>:<EmptyData text="Chưa có trải nghiệm cá nhân được ghi nhận."/>}</section>
    <section className="section-card ability-profile" id="abilities"><div className="section-title"><div><Pill>06</Pill><h2>Hồ sơ năng lực</h2></div><Pill tone={abilities.length?'success':'outline'}>{abilities.length?'Có dữ liệu đánh giá':'Chưa có dữ liệu'}</Pill></div><p>Tám năng lực được tổng hợp từ bài đánh giá và mini-task. Kết quả chưa thể hiện không được xem là điểm yếu.</p>{abilities.length?<><div className="ability-dashboard"><AbilityRadar abilities={abilities}/><div className="ability-selector" role="list">{ABILITY_CATALOG.map(([id,label])=>{const item=abilities.find(entry=>entry.abilityId===id);return <button key={id} className={selectedAbility===id?'selected':''} onClick={()=>setSelectedAbility(id)}><span>{label}</span><b>{item?.level||'Chưa có dữ liệu'}</b><i style={{width:`${item?.score?item.score/3*100:0}%`}}/></button>})}</div></div><div className="ability-evidence"><div><small>Năng lực đang xem</small><h3>{selected?.abilityName||ABILITY_CATALOG.find(([id])=>id===selectedAbility)?.[1]}</h3></div>{selected?<><div className="ability-metrics"><span><small>Kết quả hiện tại</small><b>{selected.level}</b></span><span><small>Điểm thể hiện</small><b>{selected.score}/3</b></span><span><small>Độ tin cậy</small><b>{Math.round((selected.confidence||0)*100)}%</b></span></div><p>{selected.reasoning}</p><div className="evidence-chips"><b>Bằng chứng</b>{(selected.evidenceQuestionIds||[]).map(id=><code key={id}>{id}</code>)}</div><div className="not-observed"><b>Điểm chưa thể hiện</b><span>Không tự suy diễn khi chưa có đủ cơ hội hoặc bằng chứng trong bài đánh giá.</span></div></>:<EmptyData text="Năng lực này chưa có đủ bằng chứng để đánh giá."/>}</div></>:<EmptyData text="Hồ sơ năng lực sẽ xuất hiện sau khi AI hoàn tất phân tích."/>}</section>
    <section className="confirm-section" id="confirm"><div><div className="eyebrow">Bước cuối</div><h2>Xác nhận hồ sơ</h2><p>Kiểm tra các thành phần trước khi xem nghề gợi ý. Nếu chỉnh sửa sau này, hệ thống sẽ yêu cầu xác nhận lại.</p><div className="profile-checklist">{checklist.map(([label,done])=><div key={label} className={done?'done':''}><span>{done?'✓':'—'}</span><b>{label}</b></div>)}</div></div><button className="primary" disabled={!checklist.every(([,done])=>done)} onClick={confirmProfile}>Xác nhận hồ sơ và xem nghề gợi ý <span>→</span></button></section>
  </div></div></main></>
}
