import React, { useEffect, useState } from 'react';
import { api, setAccessToken } from '../lib/api';
import { go } from '../lib/navigation';

const ROLE_NAMES={SUPERADMIN:'Quản trị hệ thống',TENANT_ADMIN:'Quản trị trường',HOMEROOM_TEACHER:'Giáo viên / Giảng viên',STUDENT:'Học sinh / Sinh viên',PROFESSIONAL:'Người đi làm'};
const MENU={SUPERADMIN:['Tổng quan','Trường học','Audit log'],TENANT_ADMIN:['Tổng quan trường','Giáo viên / Giảng viên','Lớp học','Người học'],HOMEROOM_TEACHER:['Lớp của tôi','Người học','Trạng thái đánh giá'],STUDENT:['Hồ sơ','Năng lực','Nghề phù hợp','Lộ trình'],PROFESSIONAL:['Hồ sơ & CV','Năng lực','Nghề phù hợp','Lộ trình']};

function Field({label,...props}){return <label><span>{label}</span><input {...props}/></label>}
function SelectField({label,children,...props}){return <label><span>{label}</span><select {...props}>{children}</select></label>}

export function Dashboard({user,onLogout}) {
  const [items,setItems]=useState([]); const [message,setMessage]=useState(''); const [selectedTenant,setSelectedTenant]=useState('');
  const [form,setForm]=useState({code:'',name:'',email:'',display_name:'',grade_level:'',school_year:'2026-2027',profile_type:'HIGH_SCHOOL'});
  const load=async()=>{try{if(user.role==='SUPERADMIN')setItems(await api('/api/admin/tenants'));if(user.role==='TENANT_ADMIN')setItems(await api('/api/school/classes'));if(user.role==='HOMEROOM_TEACHER')setItems(await api('/api/teacher/classes'))}catch(e){setMessage(e.message)}};
  useEffect(()=>{load()},[user.role]);
  const submit=async(type)=>{setMessage('');try{let result;if(type==='tenant')result=await api('/api/admin/tenants',{method:'POST',body:JSON.stringify({code:form.code,name:form.name})});if(type==='admin')result=await api(`/api/admin/tenants/${selectedTenant}/admins/invitations`,{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name})});if(type==='teacher')result=await api('/api/school/teachers/invitations',{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name})});if(type==='class')result=await api('/api/school/classes',{method:'POST',body:JSON.stringify({name:form.name,grade_level:form.grade_level,school_year:form.school_year})});if(type==='student')result=await api(`/api/teacher/classes/${selectedTenant}/students/invitations`,{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name,profile_type:form.profile_type})});setMessage(result?.acceptToken?`Đã tạo lời mời. Token thử nghiệm: ${result.acceptToken}`:'Đã tạo thành công.');load()}catch(e){setMessage(e.message)}};
  const logout=async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>null);setAccessToken(null);onLogout();go('/login')};
  if(['STUDENT','PROFESSIONAL'].includes(user.role))return <div className="role-shell"><RoleSidebar user={user} logout={logout}/><main className="role-main"><div className="dashboard-welcome"><span>{ROLE_NAMES[user.role]}</span><h1>Xin chào, {user.displayName||user.email}</h1><p>Tài khoản đã được xác thực. Tiếp tục với hồ sơ định hướng nghề nghiệp của riêng bạn.</p><button className="primary" onClick={()=>go('/profile')}>Mở hồ sơ của tôi →</button></div></main></div>;
  return <div className="role-shell"><RoleSidebar user={user} logout={logout}/><main className="role-main"><div className="role-top"><div><span>{ROLE_NAMES[user.role]}</span><h1>{user.role==='SUPERADMIN'?'Quản trị Career Compass':user.role==='TENANT_ADMIN'?'Không gian nhà trường':'Các lớp đang phụ trách'}</h1></div><div className="role-avatar">{(user.displayName||user.email).slice(0,2).toUpperCase()}</div></div>{message&&<div className="dashboard-notice">{message}</div>}<section className="dashboard-grid"><div className="dashboard-list"><div className="section-title"><h2>{user.role==='SUPERADMIN'?'Danh sách trường':user.role==='TENANT_ADMIN'?'Danh sách lớp':'Lớp của tôi'}</h2><b>{items.length}</b></div>{items.map(item=><button key={item.id} onClick={()=>setSelectedTenant(item.id)} className={selectedTenant===item.id?'selected':''}><div><b>{item.name}</b><small>{item.code||item.grade_level||item.school_year}</small></div><span>→</span></button>)}{!items.length&&<p>Chưa có dữ liệu.</p>}</div><div className="provision-card"><span className="eyebrow">Cấp tài khoản từ trên xuống</span>{user.role==='SUPERADMIN'&&<><h2>Tạo trường mới</h2><Field label="Mã trường" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/><Field label="Tên trường" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><button className="primary" onClick={()=>submit('tenant')}>Tạo trường</button><hr/><h2>Mời quản trị viên trường</h2><Field label="Tên" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="ghost" disabled={!selectedTenant} onClick={()=>submit('admin')}>Tạo lời mời Tenant Admin</button></>}{user.role==='TENANT_ADMIN'&&<><h2>Mời giáo viên</h2><Field label="Tên giáo viên" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary" onClick={()=>submit('teacher')}>Tạo lời mời</button><hr/><h2>Tạo lớp học</h2><Field label="Tên lớp" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Khối" value={form.grade_level} onChange={e=>setForm({...form,grade_level:e.target.value})}/><Field label="Năm học" value={form.school_year} onChange={e=>setForm({...form,school_year:e.target.value})}/><button className="ghost" onClick={()=>submit('class')}>Tạo lớp</button></>}
{user.role==='HOMEROOM_TEACHER'&&<><h2>Cấp tài khoản người học</h2><p>Có thể thêm học sinh hoặc sinh viên vào lớp mà giáo viên/giảng viên đang được phân công.</p><SelectField label="Đối tượng" value={form.profile_type} onChange={e=>setForm({...form,profile_type:e.target.value})}><option value="HIGH_SCHOOL">Học sinh THPT</option><option value="UNIVERSITY">Sinh viên đại học</option></SelectField><Field label="Tên học sinh / sinh viên" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary" disabled={!selectedTenant} onClick={()=>submit('student')}>Tạo lời mời người học</button>{!selectedTenant&&<small>Hãy chọn lớp bên trái trước.</small>}</>}</div></section></main></div>;
}

function RoleSidebar({user,logout}){return <aside className="role-sidebar"><div className="role-brand"><i>CC</i><b>Career Compass</b></div><div className="role-identity"><small>Đang đăng nhập</small><b>{user.displayName||user.email}</b><span>{ROLE_NAMES[user.role]}</span></div><nav>{MENU[user.role].map((item,index)=><button className={index===0?'active':''} key={item}><span>{String(index+1).padStart(2,'0')}</span>{item}</button>)}</nav><button className="role-logout" onClick={logout}>Đăng xuất</button></aside>}
