import React, { useEffect, useState } from 'react';
import { api, setAccessToken } from '../lib/api';
import { go } from '../lib/navigation';

const ROLE_NAMES={SUPERADMIN:'Quản trị hệ thống',TENANT_ADMIN:'Quản trị trường',HOMEROOM_TEACHER:'Giáo viên / Giảng viên',STUDENT:'Học sinh / Sinh viên',PROFESSIONAL:'Người đi làm'};
const MENUS={SUPERADMIN:[['tenants','Trường học'],['audit','Audit log']],TENANT_ADMIN:[['teachers','Giáo viên / Giảng viên'],['classes','Lớp học']],HOMEROOM_TEACHER:[['classes','Lớp của tôi'],['students','Người học'],['status','Trạng thái đánh giá']],STUDENT:[['/profile','Hồ sơ'],['/assessment','Năng lực'],['/careers','Nghề phù hợp'],['/roadmap','Lộ trình']],PROFESSIONAL:[['/profile','Hồ sơ & CV'],['/assessment','Năng lực'],['/careers','Nghề phù hợp'],['/roadmap','Lộ trình']]};
function Field({label,...props}){return <label><span>{label}</span><input {...props}/></label>}
function SelectField({label,children,...props}){return <label><span>{label}</span><select {...props}>{children}</select></label>}
const displayName=item=>item.display_name||item.displayName||item.name||item.email||item.action||'Không có tên';

export function Dashboard({user,onLogout}) {
  const menu=MENUS[user.role]||[];const [tab,setTab]=useState(menu[0]?.[0]);const [items,setItems]=useState([]);const [teachers,setTeachers]=useState([]);const [classes,setClasses]=useState([]);const [message,setMessage]=useState('');const [selectedId,setSelectedId]=useState('');const [archived,setArchived]=useState(false);
  const [form,setForm]=useState({code:'',name:'',email:'',display_name:'',grade_level:'',school_year:'2026-2027',profile_type:'HIGH_SCHOOL',teacher_id:'',starts_at:new Date().toISOString().slice(0,10)});
  const load=async()=>{setMessage('');try{if(user.role==='SUPERADMIN')setItems(await api(tab==='audit'?'/api/admin/audit-logs':`/api/admin/tenants?status=${archived?'DISABLED':'ACTIVE'}`));if(user.role==='TENANT_ADMIN'){const [activeTeachers,cs]=await Promise.all([api('/api/school/teachers?status=ACTIVE'),api('/api/school/classes')]);setTeachers(activeTeachers);setClasses(cs);setItems(tab==='teachers'?(archived?await api('/api/school/teachers?status=DISABLED'):activeTeachers):cs)}if(user.role==='HOMEROOM_TEACHER'){const cs=await api('/api/teacher/classes');setClasses(cs);const classId=selectedId||cs[0]?.id||'';if(!selectedId&&classId)setSelectedId(classId);if(tab==='classes'||!classId)setItems(cs);else setItems(await api(`/api/teacher/classes/${classId}/${tab==='status'?'assessment-status':archived?'removed-students':'students'}`))}}catch(error){setMessage(error.message)}};
  useEffect(()=>{load()},[user.role,tab,selectedId,archived]);
  const submit=async type=>{setMessage('');try{let result;if(type==='tenant')result=await api('/api/admin/tenants',{method:'POST',body:JSON.stringify({code:form.code,name:form.name})});if(type==='admin')result=await api(`/api/admin/tenants/${selectedId}/admins/invitations`,{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name})});if(type==='teacher')result=await api('/api/school/teachers/invitations',{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name})});if(type==='class')result=await api('/api/school/classes',{method:'POST',body:JSON.stringify({name:form.name,grade_level:form.grade_level,school_year:form.school_year})});if(type==='assignment')result=await api(`/api/school/classes/${selectedId}/assignments`,{method:'POST',body:JSON.stringify({teacher_id:form.teacher_id,starts_at:form.starts_at,ends_at:null})});if(type==='student')result=await api(`/api/teacher/classes/${selectedId}/students/invitations`,{method:'POST',body:JSON.stringify({email:form.email,display_name:form.display_name,profile_type:form.profile_type})});setMessage(result?.acceptToken?`Đã tạo lời mời. Token demo: ${result.acceptToken}`:'Đã tạo thành công.');await load()}catch(error){setMessage(error.message)}};
  const remove=async(kind,id)=>{const labels={tenant:'trường này và khóa toàn bộ tài khoản thuộc trường',teacher:'giáo viên này và thu hồi phân công',student:'học sinh này khỏi lớp'};if(!confirm(`Bạn chắc chắn muốn xóa ${labels[kind]}?`))return;try{const path=kind==='tenant'?`/api/admin/tenants/${id}`:kind==='teacher'?`/api/school/teachers/${id}`:`/api/teacher/classes/${selectedId}/students/${id}`;await api(path,{method:'DELETE'});setMessage('Đã xử lý thành công.');if(id===selectedId)setSelectedId('');await load()}catch(error){setMessage(error.message)}};
  const restore=async(kind,id)=>{try{const path=kind==='tenant'?`/api/admin/tenants/${id}/restore`:kind==='teacher'?`/api/school/teachers/${id}/restore`:`/api/teacher/classes/${selectedId}/students/${id}/restore`;await api(path,{method:'PATCH'});setMessage('Đã khôi phục thành công.');await load()}catch(error){setMessage(error.message)}};
  const logout=async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>null);setAccessToken(null);onLogout();go('/login')};
  if(['STUDENT','PROFESSIONAL'].includes(user.role))return <div className="role-shell"><RoleSidebar user={user} menu={menu} active={tab} onSelect={go} logout={logout}/><main className="role-main"><div className="dashboard-welcome"><span>{ROLE_NAMES[user.role]}</span><h1>Xin chào, {user.displayName||user.email}</h1><p>Tài khoản đã được xác thực. Tiếp tục với hồ sơ định hướng nghề nghiệp của riêng bạn.</p><button className="primary" onClick={()=>go('/profile')}>Mở hồ sơ của tôi →</button></div></main></div>;
  const title=tab==='tenants'?'Trường học':tab==='audit'?'Nhật ký hệ thống':tab==='teachers'?'Giáo viên / Giảng viên':tab==='classes'?(user.role==='HOMEROOM_TEACHER'?'Lớp của tôi':'Lớp học'):tab==='students'?'Người học':'Trạng thái đánh giá';
  const canArchive=(user.role==='SUPERADMIN'&&tab==='tenants')||(user.role==='TENANT_ADMIN'&&tab==='teachers')||(user.role==='HOMEROOM_TEACHER'&&tab==='students');
  return <div className="role-shell"><RoleSidebar user={user} menu={menu} active={tab} onSelect={key=>{setArchived(false);setTab(key)}} logout={logout}/><main className="role-main"><div className="role-top"><div><span>{ROLE_NAMES[user.role]}</span><h1>{title}</h1></div><div className="role-avatar">{(user.displayName||user.email).slice(0,2).toUpperCase()}</div></div>{message&&<div className="dashboard-notice">{message}</div>}<div className="dashboard-controls">{user.role==='HOMEROOM_TEACHER'&&tab!=='classes'&&<div className="dashboard-toolbar"><SelectField label="Chọn lớp" value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{classes.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</SelectField></div>}{canArchive&&<div className="archive-toggle"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Đang hoạt động</button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Đã khóa / đã gỡ</button></div>}</div>
  <section className="dashboard-grid"><div className="dashboard-list"><div className="section-title"><h2>{archived&&canArchive?`${title} đã khóa / đã gỡ`:title}</h2><b>{items.length}</b></div>{items.map(item=>{const id=item.id||item.student_id;const selectable=(user.role==='SUPERADMIN'&&tab==='tenants')||(user.role==='TENANT_ADMIN'&&tab==='classes')||(user.role==='HOMEROOM_TEACHER'&&tab==='classes');const kind=user.role==='SUPERADMIN'?'tenant':user.role==='TENANT_ADMIN'?'teacher':'student';return <div className={`dashboard-row ${selectedId===id?'selected':''}`} key={id||item.created_at}><button onClick={()=>selectable&&setSelectedId(id)}><b>{displayName(item)}</b><small>{item.code||item.email||item.grade_level||item.assessment_status||item.resource_type}</small></button>{canArchive&&(archived?<button className="restore-text" onClick={()=>restore(kind,id)}>Khôi phục</button>:<button className="danger-text" onClick={()=>remove(kind,id)}>{kind==='student'?'Gỡ khỏi lớp':'Xóa'}</button>)}</div>})}{!items.length&&<p>Chưa có dữ liệu.</p>}</div>
  <div className="provision-card">{user.role==='SUPERADMIN'&&tab==='tenants'&&<><span className="eyebrow">Quản lý trường</span><h2>Tạo trường mới</h2><Field label="Mã trường" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/><Field label="Tên trường" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><button className="primary" onClick={()=>submit('tenant')}>Tạo trường</button><hr/><h2>Mời quản trị viên trường</h2><Field label="Tên" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="ghost" disabled={!selectedId} onClick={()=>submit('admin')}>Tạo lời mời Tenant Admin</button></>}{user.role==='SUPERADMIN'&&tab==='audit'&&<><span className="eyebrow">Theo dõi hệ thống</span><h2>Audit log</h2><p>Hiển thị 200 hoạt động mới nhất từ API.</p></>}
  {user.role==='TENANT_ADMIN'&&tab==='teachers'&&<><span className="eyebrow">Nhân sự</span><h2>Mời giáo viên</h2><Field label="Tên giáo viên" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary" onClick={()=>submit('teacher')}>Tạo lời mời</button></>}{user.role==='TENANT_ADMIN'&&tab==='classes'&&<><span className="eyebrow">Lớp học</span><h2>Tạo lớp</h2><Field label="Tên lớp" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Khối" value={form.grade_level} onChange={e=>setForm({...form,grade_level:e.target.value})}/><Field label="Năm học" value={form.school_year} onChange={e=>setForm({...form,school_year:e.target.value})}/><button className="primary" onClick={()=>submit('class')}>Tạo lớp</button><hr/><h2>Phân công giáo viên</h2><SelectField label="Giáo viên" value={form.teacher_id} onChange={e=>setForm({...form,teacher_id:e.target.value})}><option value="">Chọn giáo viên</option>{teachers.filter(t=>t.status==='ACTIVE').map(t=><option key={t.id} value={t.id}>{displayName(t)}</option>)}</SelectField><Field label="Ngày bắt đầu" type="date" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><button className="ghost" disabled={!selectedId||!form.teacher_id} onClick={()=>submit('assignment')}>Phân công vào lớp đã chọn</button></>}
  {user.role==='HOMEROOM_TEACHER'&&tab==='students'&&<><span className="eyebrow">Người học</span><h2>Mời vào lớp</h2><SelectField label="Đối tượng" value={form.profile_type} onChange={e=>setForm({...form,profile_type:e.target.value})}><option value="HIGH_SCHOOL">Học sinh THPT</option><option value="UNIVERSITY">Sinh viên đại học</option></SelectField><Field label="Tên người học" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary" disabled={!selectedId} onClick={()=>submit('student')}>Tạo lời mời</button></>}{user.role==='HOMEROOM_TEACHER'&&tab==='classes'&&<><span className="eyebrow">Phân công hiện tại</span><h2>Chọn một lớp</h2><p>Sau đó mở Người học hoặc Trạng thái đánh giá ở menu bên trái.</p></>}{user.role==='HOMEROOM_TEACHER'&&tab==='status'&&<><span className="eyebrow">Tiến độ</span><h2>Trạng thái mới nhất</h2><p><b>not_started</b>: chưa làm · <b>in_progress</b>: đang làm · <b>submitted</b>: đã hoàn thành.</p></>}</div></section></main></div>;
}
function RoleSidebar({user,menu,active,onSelect,logout}){return <aside className="role-sidebar"><div className="role-brand"><i>CC</i><b>Career Compass</b></div><div className="role-identity"><small>Đang đăng nhập</small><b>{user.displayName||user.email}</b><span>{ROLE_NAMES[user.role]}</span></div><nav>{menu.map(([key,label],index)=><button onClick={()=>onSelect(key)} className={active===key?'active':''} key={key}><span>{String(index+1).padStart(2,'0')}</span>{label}</button>)}</nav><button className="role-logout" onClick={logout}>Đăng xuất</button></aside>}
