import React, { useState } from 'react';
import { HeaderAI, Pill } from '../components/common';
import { readSession, saveSession } from '../lib/session';
import { go } from '../lib/navigation';

const PROFILE_TYPES=[
  {id:'student',label:'Học sinh THPT'},
  {id:'university',label:'Sinh viên'},
  {id:'professional',label:'Người đã đi làm'},
];

const makeId=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

function StudentAcademicEditor({years,onChange}){
  const updateYear=(index,patch)=>onChange(years.map((item,i)=>i===index?{...item,...patch}:item));
  const addYear=()=>onChange([...years,{id:makeId('school-year'),schoolYear:'',grade:'',subjects:[]}]);
  return <div className="academic-editor wide"><div className="academic-heading"><div><b>Điểm các năm học</b><span>Không có môn học tạo sẵn. Học sinh tự thêm đúng các môn đã học.</span></div><button type="button" className="ghost" onClick={addYear}>+ Thêm năm học</button></div>{years.map((year,yearIndex)=><div className="academic-period" key={year.id||yearIndex}><div className="academic-period-head"><label>Năm học<input value={year.schoolYear||''} placeholder="Ví dụ: 2025–2026" onChange={e=>updateYear(yearIndex,{schoolYear:e.target.value})}/></label><label>Lớp<select value={year.grade||''} onChange={e=>updateYear(yearIndex,{grade:e.target.value})}><option value="">Chọn lớp</option><option>10</option><option>11</option><option>12</option></select></label><button type="button" className="danger-text" onClick={()=>onChange(years.filter((_,i)=>i!==yearIndex))}>Xóa năm học</button></div><div className="subject-list">{(year.subjects||[]).map((subject,subjectIndex)=><div className="subject-row" key={subject.id||subjectIndex}><input aria-label="Tên môn học" placeholder="Tên môn học" value={subject.name||''} onChange={e=>updateYear(yearIndex,{subjects:year.subjects.map((item,i)=>i===subjectIndex?{...item,name:e.target.value}:item)})}/><input aria-label="Điểm môn học" type="number" min="0" max="10" step="0.1" placeholder="Điểm" value={subject.score??''} onChange={e=>updateYear(yearIndex,{subjects:year.subjects.map((item,i)=>i===subjectIndex?{...item,score:e.target.value}:item)})}/><button type="button" className="danger-text" onClick={()=>updateYear(yearIndex,{subjects:year.subjects.filter((_,i)=>i!==subjectIndex)})}>Xóa</button></div>)}<button type="button" className="text-btn" onClick={()=>updateYear(yearIndex,{subjects:[...(year.subjects||[]),{id:makeId('subject'),name:'',score:''}]})}>+ Thêm môn học</button></div></div>)}{!years.length&&<div className="academic-empty">Chưa có bảng điểm. Nhấn “Thêm năm học” để bắt đầu.</div>}</div>;
}
function UniversityAcademicEditor({gpa,subjects,onGpaChange,onSubjectsChange}){
  return <div className="academic-editor wide"><div className="academic-heading"><div><b>Kết quả học tập đại học</b><span>Nhập GPA và tự thêm các môn chuyên ngành đã hoàn thành.</span></div></div><label className="gpa-field">GPA hiện tại <span>Theo thang điểm của trường</span><input type="number" min="0" step="0.01" value={gpa||''} placeholder="Ví dụ: 3.45" onChange={onGpaChange}/></label><div className="subject-list">{subjects.map((subject,index)=><div className="subject-row university-subject" key={subject.id||index}><input aria-label="Tên môn chuyên ngành" placeholder="Tên môn chuyên ngành" value={subject.name||''} onChange={e=>onSubjectsChange(subjects.map((item,i)=>i===index?{...item,name:e.target.value}:item))}/><input aria-label="Điểm môn chuyên ngành" type="number" min="0" step="0.01" placeholder="Điểm" value={subject.score??''} onChange={e=>onSubjectsChange(subjects.map((item,i)=>i===index?{...item,score:e.target.value}:item))}/><button type="button" className="danger-text" onClick={()=>onSubjectsChange(subjects.filter((_,i)=>i!==index))}>Xóa</button></div>)}<button type="button" className="ghost" onClick={()=>onSubjectsChange([...subjects,{id:makeId('major-subject'),name:'',score:''}])}>+ Thêm môn chuyên ngành</button></div></div>;
}

export function CandidateProfile(){
  const [session,setSession]=useState(readSession());
  const [editing,setEditing]=useState(false);
  const [saved,setSaved]=useState(false);
  const [basic,setBasic]=useState(session.answers?.basic||{});
  const profileType=basic.profileType||'';
  const update=(field,value)=>setBasic(current=>({...current,[field]:value}));
  const save=()=>{const clean={...basic,name:(basic.name||'').trim()};const next=saveSession({displayName:clean.name||null,answers:{...(session.answers||{}),basic:clean},profileStatus:session.assessmentCompleted?'needs_reconfirmation':session.profileStatus});setSession(next);setBasic(clean);setEditing(false);setSaved(true);setTimeout(()=>setSaved(false),2500)};
  const genderLabels={male:'Nam',female:'Nữ',other:'Khác',prefer_not_to_say:'Không muốn tiết lộ'};
  const rows=[['Tên hiển thị',session.displayName||'Ẩn danh'],['Đối tượng',PROFILE_TYPES.find(item=>item.id===profileType)?.label],['Tuổi',basic.age],['Giới tính',genderLabels[basic.gender]],['Khu vực',basic.region]];
  if(profileType==='student')rows.push(['Trường',basic.school],['Lớp hiện tại',basic.grade],['Bảng điểm',basic.academicYears?.length?`${basic.academicYears.length} năm học`:null]);
  if(profileType==='university')rows.push(['Trường',basic.school],['Ngành học',basic.major],['Sinh viên năm',basic.studyYear],['GPA',basic.gpa],['Môn chuyên ngành',basic.majorSubjects?.length?`${basic.majorSubjects.length} môn`:null]);
  if(profileType==='professional')rows.push(['Công việc hiện tại',basic.currentJob],['Số năm kinh nghiệm',basic.experienceYears],['CV',basic.cvName]);
  return <><HeaderAI page="profile"/><main className="page candidate-profile"><div className="profile-head"><div><div className="eyebrow">Hồ sơ cá nhân</div><h1>{session.displayName?`Xin chào, ${session.displayName}`:'Hồ sơ ẩn danh của bạn'}</h1><p>Thông tin nền giúp hệ thống hiểu đúng bối cảnh của bạn. Kết quả năng lực và nhận định AI được quản lý riêng trong mục Năng lực.</p></div><div className="completion"><b>{rows.filter(([,value])=>value).length}/{rows.length}</b><span>thông tin đã có</span></div></div>{saved&&<div className="notice" role="status">Đã lưu thông tin hồ sơ trên thiết bị này.</div>}<div className="candidate-grid"><section className="section-card"><div className="section-title"><div><Pill>01</Pill><h2>Thông tin cơ bản</h2></div><button className="text-btn" onClick={()=>setEditing(value=>!value)}>{editing?'Hủy':'Chỉnh sửa'}</button></div>{editing?<div className="candidate-form"><label>Tên hiển thị <span>Không bắt buộc</span><input value={basic.name||''} placeholder="Để trống nếu muốn ẩn danh" onChange={e=>update('name',e.target.value)}/></label><label>Tuổi<input type="number" min="10" max="100" value={basic.age||''} onChange={e=>update('age',e.target.value)}/></label>
<label>Giới tính<select value={basic.gender||''} onChange={e=>update('gender',e.target.value)}><option value="">Chọn giới tính</option><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác</option><option value="prefer_not_to_say">Không muốn tiết lộ</option></select></label><label>Giai đoạn hiện tại<select value={profileType} onChange={e=>setBasic(current=>({...current,profileType:e.target.value,grade:'',studyYear:'',major:'',currentJob:'',experienceYears:''}))}><option value="">Chọn giai đoạn</option>{PROFILE_TYPES.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Khu vực hiện tại<input value={basic.region||''} onChange={e=>update('region',e.target.value)}/></label>
{profileType==='student'&&<><label>Trường THPT<input value={basic.school||''} onChange={e=>update('school',e.target.value)}/></label><label>Lớp hiện tại<select value={basic.grade||''} onChange={e=>update('grade',e.target.value)}><option value="">Chọn lớp</option><option>10</option><option>11</option><option>12</option></select></label><StudentAcademicEditor years={basic.academicYears||[]} onChange={value=>update('academicYears',value)}/></>}
{profileType==='university'&&<><label>Trường đại học<input value={basic.school||''} onChange={e=>update('school',e.target.value)}/></label><label>Ngành học<input value={basic.major||''} onChange={e=>update('major',e.target.value)}/></label><label>Sinh viên năm<select value={basic.studyYear||''} onChange={e=>update('studyYear',e.target.value)}><option value="">Chọn năm</option>{[1,2,3,4,5,6].map(year=><option key={year}>{year}</option>)}</select></label><UniversityAcademicEditor gpa={basic.gpa} subjects={basic.majorSubjects||[]} onGpaChange={e=>update('gpa',e.target.value)} onSubjectsChange={value=>update('majorSubjects',value)}/><label className="wide">CV <span>Bắt buộc để tạo lộ trình cho sinh viên</span><input type="file" accept=".pdf,.doc,.docx" onChange={e=>update('cvName',e.target.files?.[0]?.name||'')}/></label></>}
{profileType==='professional'&&<><label>Công việc hiện tại<input value={basic.currentJob||''} onChange={e=>update('currentJob',e.target.value)}/></label><label>Số năm kinh nghiệm<input type="number" min="0" value={basic.experienceYears||''} onChange={e=>update('experienceYears',e.target.value)}/></label><label className="wide">CV <span>Phân tích CV sẽ được kết nối với backend sau</span><input type="file" accept=".pdf,.doc,.docx" onChange={e=>update('cvName',e.target.files?.[0]?.name||'')}/></label></>}<div className="form-actions wide"><button className="ghost" onClick={()=>{setBasic(session.answers?.basic||{});setEditing(false)}}>Hủy thay đổi</button><button className="primary" onClick={save}>Lưu hồ sơ</button></div></div>:<div className="info-grid profile-info-grid">{rows.map(([label,value])=><div key={label}><small>{label}</small><b>{value||'Chưa thiết lập'}</b></div>)}</div>}</section><aside className="profile-source-card"><div><Pill tone="soft">Nguồn dữ liệu</Pill><h2>Dữ liệu nào đang được sử dụng?</h2></div><div className="source-row active"><i/><div><b>Người dùng tự khai</b><span>{rows.filter(([,value])=>value).length} trường thông tin</span></div></div><div className="source-row"><i/><div><b>Nhà trường</b><span>Chưa kết nối</span></div></div><div className="source-row"><i/><div><b>CV và AI</b><span>{basic.cvName?'Chờ backend phân tích':'Chưa có dữ liệu'}</span></div></div><button className="primary" onClick={()=>go('/abilities')}>Xem hồ sơ năng lực <span>→</span></button></aside></div></main></>
}

export function ProfileDataEditor({section,onClose,onSave,interestDraft,setInterestDraft,skillsDraft,setSkillsDraft,tendencyDraft,setTendencyDraft,experienceDraft,setExperienceDraft}){
  if(!section)return null;
  if(section==='abilities')return <div className="section-editor"><div className="editor-actions"><div><b>Cập nhật hồ sơ năng lực</b><p>Năng lực phải được cập nhật từ câu trả lời và mini-task, không chỉnh điểm thủ công.</p></div><button className="text-btn" onClick={onClose}>Đóng</button></div><button className="primary" onClick={()=>go('/assessment')}>Làm bài đánh giá cập nhật <span>→</span></button></div>;
  if(section==='interests')return <div className="section-editor"><div className="editor-actions"><b>Chỉnh sửa sở thích và giá trị</b><button className="text-btn" onClick={onClose}>Đóng</button></div><label>Hoạt động đang yêu thích<textarea value={interestDraft.current.join(', ')} onChange={e=>setInterestDraft({...interestDraft,current:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Hoạt động muốn khám phá<textarea value={interestDraft.exploration.join(', ')} onChange={e=>setInterestDraft({...interestDraft,exploration:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Giá trị nghề nghiệp theo thứ tự ưu tiên<textarea value={interestDraft.values.join(', ')} onChange={e=>setInterestDraft({...interestDraft,values:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><button className="primary" onClick={()=>onSave('interests')}>Lưu sở thích và giá trị</button></div>;
  if(section==='skills')return <div className="section-editor"><div className="editor-actions"><b>Chỉnh sửa kỹ năng</b><button className="text-btn" onClick={onClose}>Đóng</button></div>{skillsDraft.map((skill,index)=><div className="editor-card" key={index}><div className="editor-row"><input aria-label="Tên kỹ năng" placeholder="Tên kỹ năng" value={skill.name||''} onChange={e=>setSkillsDraft(skillsDraft.map((item,i)=>i===index?{...item,name:e.target.value}:item))}/><select aria-label="Mức kỹ năng" value={skill.level??1} onChange={e=>setSkillsDraft(skillsDraft.map((item,i)=>i===index?{...item,level:Number(e.target.value)}:item))}><option value="1">Cơ bản</option><option value="2">Khá</option><option value="3">Tốt</option></select></div><textarea aria-label="Bối cảnh sử dụng" placeholder="Đã sử dụng trong môn học hoặc dự án nào?" value={skill.context||''} onChange={e=>setSkillsDraft(skillsDraft.map((item,i)=>i===index?{...item,context:e.target.value}:item))}/><button className="danger-text" onClick={()=>setSkillsDraft(skillsDraft.filter((_,i)=>i!==index))}>Xóa kỹ năng</button></div>)}<div className="editor-actions"><button className="ghost" onClick={()=>setSkillsDraft([...skillsDraft,{name:'',level:1,context:''}])}>Thêm kỹ năng</button><button className="primary" onClick={()=>onSave('skills')}>Lưu kỹ năng</button></div></div>;
  if(section==='tendencies'){const defaults=[['collaboration','Làm việc cùng nhóm'],['structure','Môi trường có cấu trúc'],['change','Thích nghi với thay đổi'],['data_focus','Tập trung vào dữ liệu'],['communication','Giao tiếp thường xuyên'],['method','Tự tìm phương pháp']];const rows=tendencyDraft.length?tendencyDraft:defaults.map(([id,name])=>({id,name,value:1}));return <div className="section-editor"><div className="editor-actions"><b>Cập nhật xu hướng làm việc</b><button className="text-btn" onClick={onClose}>Đóng</button></div>{rows.map((item,index)=><label className="editor-row" key={item.id}><span>{item.name}</span><select value={item.value} onChange={e=>setTendencyDraft(rows.map((row,i)=>i===index?{...row,value:Number(e.target.value)}:row))}><option value="1">Không đúng</option><option value="2">Đúng một phần</option><option value="3">Khá đúng</option><option value="4">Rất đúng</option></select></label>)}<button className="primary" onClick={()=>{if(!tendencyDraft.length)setTendencyDraft(rows);setTimeout(()=>onSave('tendencies'),0)}}>Lưu xu hướng</button></div>}
  if(section==='experiences')return <div className="section-editor"><div className="editor-actions"><b>Chỉnh sửa trải nghiệm</b><button className="text-btn" onClick={onClose}>Đóng</button></div>{experienceDraft.map((item,index)=><div className="editor-card" key={item.id||index}><input placeholder="Tên hoạt động" value={item.title||''} onChange={e=>setExperienceDraft(experienceDraft.map((row,i)=>i===index?{...row,title:e.target.value}:row))}/><input placeholder="Vai trò" value={item.role||''} onChange={e=>setExperienceDraft(experienceDraft.map((row,i)=>i===index?{...row,role:e.target.value}:row))}/><textarea placeholder="Vai trò và việc đã làm" value={item.description||''} onChange={e=>setExperienceDraft(experienceDraft.map((row,i)=>i===index?{...row,description:e.target.value}:row))}/><textarea placeholder="Điều nhận ra về bản thân" value={item.reflection||''} onChange={e=>setExperienceDraft(experienceDraft.map((row,i)=>i===index?{...row,reflection:e.target.value}:row))}/><button className="danger-text" onClick={()=>setExperienceDraft(experienceDraft.filter((_,i)=>i!==index))}>Xóa trải nghiệm</button></div>)}<div className="editor-actions"><button className="ghost" onClick={()=>setExperienceDraft([...experienceDraft,{id:`experience-${Date.now()}`,title:'',role:'',description:'',liked_aspects:[],disliked_aspects:[],reflection:''}])}>Thêm trải nghiệm</button><button className="primary" onClick={()=>onSave('experiences')}>Lưu trải nghiệm</button></div></div>;
  return null;
}


