import React, { useState } from 'react';
import initialMock from '../mocks/initial_analysis_response.json';
import planMock from '../mocks/plan_generation_response.json';
import followupMock from '../mocks/followup_evaluation_response.json';
import { adaptAnalysisResponse } from '../contracts/responseAdapter';
import { CONTENT_MODE_LABELS, OUTCOME_LABELS, ABILITY_LEVEL_LABELS, GAP_TYPE_LABELS, PRIORITY_LABELS, WARNING_SEVERITY_LABELS, enumLabel } from '../contracts/responseLabels';
import { companionApi } from '../lib/companionApi';
import { HeaderAI } from '../components/common';

const formatScore = value => new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 2 }).format(Number(value));
const safeDisplayName = value => /(EVIDENCE_|SKILL_|CAREER_GROUP_)/.test(value || '') ? 'Nội dung chưa có tên hiển thị' : value;
const outcomeLabel = value => OUTCOME_LABELS[value] || (/^[a-z]+(?:_[a-z]+)+$/.test(value || '') ? 'Chưa xác định' : value);
const contentModeLabel = payload => enumLabel(CONTENT_MODE_LABELS, payload?.result_metadata?.content_mode);

function Warnings({items=[]}) { if (!items.length) return null; return <section className="contract-section"><h2>Cảnh báo và lưu ý</h2><div className="contract-warnings">{items.map(item=><article key={item.code} className={item.severity}><span>{enumLabel(WARNING_SEVERITY_LABELS,item.severity)}</span><h3>{item.title}</h3><p>{item.message}</p>{item.action&&<small>Gợi ý: {item.action}</small>}</article>)}</div></section>; }
function NextSteps({items=[]}) { if (!items.length) return null; return <section className="contract-section"><h2>Bước tiếp theo</h2><div className="contract-next">{items.map(item=><article key={item.id}><span>{enumLabel(PRIORITY_LABELS,item.priority)}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>; }

export function ResponseContractPreview() {
  const [mode,setMode]=useState('api');
  const [analysis,setAnalysis]=useState(null); const [plan,setPlan]=useState(null); const [followup,setFollowup]=useState(null);
  const [detail,setDetail]=useState(null); const [reassessment,setReassessment]=useState(null); const [feedback,setFeedback]=useState(null);
  const [loading,setLoading]=useState(''); const [error,setError]=useState('');
  const run=async(label, action)=>{setLoading(label);setError('');try{return await action();}catch(reason){setError(reason.message);return null;}finally{setLoading('');}};
  const analyze=()=>run('Đang phân tích hồ sơ…',async()=>{const raw=mode==='api'?await companionApi.analyze():initialMock;setAnalysis(adaptAnalysisResponse(raw));setPlan(null);setFollowup(null);return raw;});
  const generatePlan=()=>run('Đang tạo kế hoạch…',async()=>{const raw=mode==='api'?await companionApi.plan(analysis.analysisId):planMock;setPlan(adaptAnalysisResponse(raw));return raw;});
  const expand=()=>run('Đang mở hướng dẫn…',async()=>{if(mode==='mock'){const sample={content_id:'mock_detail',source_task_id:'mock',title:'Hướng dẫn mẫu',total_minutes:20,steps:[{step_number:1,title:'Đọc yêu cầu',instruction:'Xác định dữ kiện chính.',estimated_minutes:5},{step_number:2,title:'Thực hành',instruction:'Hoàn thành nhiệm vụ mẫu.',estimated_minutes:15}],result_metadata:{content_mode:'template_fallback'}};setDetail(sample);return sample;}const task=plan.activities[0];const raw=await companionApi.expandPlan(plan.planId,task.id);setDetail(raw);return raw;});
  const reassess=()=>run('Đang tạo bài đánh giá lại…',async()=>{if(mode==='mock'){const sample={assessment_id:'mock',target_skill_id:'SKILL_TRIG_TRANSFORMATION',questions:[{question_id:'mock_q1',skill_id:'SKILL_TRIG_TRANSFORMATION',prompt:'Cách kiểm tra phù hợp nhất trước khi kết luận từ một biểu đồ là gì?',options:['Đối chiếu nguồn và thang đo','Chỉ nhìn xu hướng nổi bật','Bỏ qua dữ liệu còn thiếu'],correct_answer:'Đối chiếu nguồn và thang đo'}],total_score:10,result_metadata:{content_mode:'template_fallback'}};setReassessment(sample);return sample;}const task=plan.activities.find(item=>item.skillId)||plan.activities[0];const raw=await companionApi.reassessment(plan.planId,task.skillId);setReassessment(raw);return raw;});
  const showFeedback=()=>run('Đang tạo phản hồi…',async()=>{const question=reassessment.questions[0];if(mode==='mock'){const sample={summary:'Câu trả lời chưa đúng; hãy kiểm tra lại quy tắc.',graded_answer:{is_correct:false},result_metadata:{content_mode:'template_fallback'}};setFeedback(sample);return sample;}const raw=await companionApi.feedback(question);setFeedback(raw);return raw;});
  const simulate=()=>run('Đang mô phỏng tuần 3…',async()=>{const raw=mode==='api'?await companionApi.followup(analysis.analysisId):followupMock;setFollowup(adaptAnalysisResponse(raw));return raw;});
  const reset=()=>run('Đang reset…',async()=>{if(mode==='api')await companionApi.reset();setAnalysis(null);setPlan(null);setDetail(null);setReassessment(null);setFeedback(null);setFollowup(null);});
  const switchMode=value=>{setMode(value);setAnalysis(null);setPlan(null);setDetail(null);setReassessment(null);setFeedback(null);setFollowup(null);setError('');};

  return <><HeaderAI page="companion"/><main className="contract-preview">
    <header className="contract-header"><div><span className="eyebrow">Student Companion · Hành trình phát triển</span><h1>Hồ sơ Nguyễn Minh Anh</h1><p>Phân tích năng lực, lập kế hoạch và theo dõi thay đổi trong một hành trình liền mạch.</p></div><nav aria-label="Nguồn dữ liệu"><button disabled={!!loading} className={mode==='api'?'active':''} onClick={()=>switchMode('api')}>API thật</button><button disabled={!!loading} className={mode==='mock'?'active':''} onClick={()=>switchMode('mock')}>Dữ liệu minh họa</button></nav></header>
    <div className={`notice ${mode==='api'?'success':'warning'}`}>{mode==='api'?'Đang dùng backend Companion API.':'Dữ liệu minh họa · tách biệt với dữ liệu API.'}</div>
    {loading&&<div className="notice"><div className="loading-ring"/>{loading}</div>}{error&&<div className="notice warning"><b>Không thể hoàn tất</b><p>{error}</p></div>}
    {!analysis&&<section className="contract-hero"><div><span>Học sinh đã chọn</span><h2>Nguyễn Minh Anh</h2><p>Hồ sơ phiên bản 1, ngân sách tuần 45 phút.</p></div><button className="primary" disabled={!!loading} onClick={analyze}>Phân tích hồ sơ</button></section>}
    {analysis&&<><section className="contract-section"><div className="contract-title-row"><h2>Hồ sơ năng lực</h2><button className="primary" onClick={generatePlan} disabled={!!loading}>Tạo kế hoạch</button></div>{analysis.marketMessage&&<div className="notice warning">{analysis.marketMessage}</div>}<div className="contract-abilities">{analysis.abilities.map(item=><article key={item.id}><div><h3>{safeDisplayName(item.displayName)}</h3><span>{enumLabel(ABILITY_LEVEL_LABELS,item.level)}</span></div><div className="contract-bar"><i style={{width:`${item.score}%`}}/></div><b>{formatScore(item.score)}/{formatScore(item.maxScore)}</b><p>{item.explanation}</p></article>)}</div></section><section className="contract-section"><h2>Các khoảng trống cần cải thiện</h2><div className="contract-gaps">{analysis.gaps.map(item=><article key={item.id} className={item.type}><span>{enumLabel(GAP_TYPE_LABELS,item.type)}</span><h3>{safeDisplayName(item.subject.displayName)}</h3><p>{item.description}</p><small>Ưu tiên: {enumLabel(PRIORITY_LABELS,item.priority)}</small></article>)}</div></section><Warnings items={analysis.warnings}/></>}
    {plan&&<section className="contract-section"><div className="contract-title-row"><h2>Kế hoạch {plan.estimatedMinutes} phút</h2><button className="ghost" disabled={!!loading} onClick={expand}>Xem hướng dẫn chi tiết</button></div><div className="contract-weeks">{plan.weeks.map(week=><article key={week.weekNumber}><div className="week-number">{String(week.weekNumber).padStart(2,'0')}</div><div><span>{week.estimatedMinutes} phút</span><h3>{week.title}</h3><p>{week.objective}</p>{week.activities.map(activity=><div className="contract-activity" key={activity.id}><b>{activity.title}</b><small>{activity.estimatedMinutes} phút</small></div>)}</div></article>)}</div>{detail&&<div className="notice success"><b>{contentModeLabel(detail)}</b><h3>{detail.title}</h3>{detail.steps.map(step=><p key={step.step_number}><b>{step.step_number}. {step.title}</b> — {step.instruction}</p>)}<button className="ghost" disabled={!!loading} onClick={reassess}>Tạo bài đánh giá lại</button></div>}</section>}
    {reassessment&&<section className="contract-section"><div className="contract-title-row"><h2>Đánh giá lại · {reassessment.questions.length} câu</h2><span className="eyebrow">{contentModeLabel(reassessment)}</span></div><p>{reassessment.questions[0].prompt}</p><div className="reassessment-options">{reassessment.questions[0].options?.map(option=><button disabled={!!loading} key={option}>{option}</button>)}</div><button className="ghost" disabled={!!loading} onClick={showFeedback}>Hiển thị phản hồi mẫu cho câu sai</button>{feedback&&<div className="notice warning"><b>Kết quả: chưa đúng</b><p>{feedback.summary}</p></div>}<button className="primary" disabled={!!loading} onClick={simulate}>Mô phỏng tuần 3</button></section>}
    {followup&&<section className="contract-section"><div className="contract-title-row"><h2>Trước và sau</h2><b>{followup.progressPercentage===100?'Đã hoàn tất chu kỳ đánh giá':`${formatScore(followup.progressPercentage)}% chu kỳ đánh giá`}</b></div><div className="contract-comparisons">{followup.comparisons.map(item=><article key={item.subject.id}><h3>{safeDisplayName(item.subject.displayName)}</h3><div className="compare-values"><span><small>Trước</small><b>{formatScore(item.before)}/{formatScore(item.maxValue)}</b></span><i>→</i><span><small>Sau</small><b>{formatScore(item.after)}/{formatScore(item.maxValue)}</b></span><strong>{item.delta>=0?'+':''}{formatScore(item.delta)}</strong></div><p>{outcomeLabel(item.interpretation)}</p></article>)}</div><NextSteps items={followup.nextSteps}/><button className="ghost" disabled={!!loading} onClick={reset}>Đặt lại hành trình</button></section>}
  </main></>;
}
